# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Jobs triggered on workflow run.
jobs:
  build/release-docker:
    runs-on: ubuntu-latest
    
    # this job will be played against each tuple of this matrix
    strategy:
      matrix:
        include:
          - image-name: frontend
            build-context: frontend/
          
          - image-name: backend
            build-context: backend/

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Install QEMU to emulate different architecture (required to use buildx for ARM)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # Install docker buildx to build image for multiple architectures
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.3.0
        with:
          # Buildx version. (eg. v0.3.0)
          version: v0.3.0
          
      # build and publish image for multiple architectures
      - name: Build and publish
        run: docker buildx build --platform linux/amd64,linux/arm64 .
